name: Create index backup

on:
  schedule:
    - cron: '6 7 * * *'  # Schedule at 7:06 am UTC
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  download-process-index-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download and extract latest htmlq release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/ericchiang/pup/releases/latest | grep "tag_name" | cut -d'"' -f4)
          wget -qO /tmp/pup.zip https://github.com/ericchiang/pup/releases/download/${LATEST_RELEASE}/pup_${LATEST_RELEASE}_linux_amd64.zip
          unzip /tmp/pup.zip
          chmod u+x pup

      - name: Process webpage and commit changes
        run: |
          curl -s https://www.srrdb.com/pre/index > /tmp/index.html
          cat /tmp/index.html | ./pup --color 'table > tbody > tr > td:first-child > a text{}' > /tmp/day.txt
          cat /tmp/index.html | ./pup --color 'table > tbody > tr > td:first-child > a attr{href}' > /tmp/href.txt
          paste -d',' /tmp/day.txt /tmp/href.txt > data-index.csv
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add data-index.csv
          git commit -m "Update data-index.csv" && git push || echo "No changes to commit"

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
